services:
  water-back:
    image: water-back
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
